#!/usr/bin/env bash
# Script that starts nginx as nginx user
chmod 644 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill -9 apache
sudo -u nginx service nginx restart
